---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: imsonu152
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "imsonu2030/scientific-calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Remove existing container
      shell: docker stop scientific-calculator || true && docker rm scientific-calculator || true
        
    - name: Running container
      shell: docker run -d --name scientific-calculator-$(date +%s) -p 3000:3000 -p 5000:5000 scientific-calculator