---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: imsonu152
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "imsonu2030/scientific-calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Check if container exists
      shell: docker ps -a --format '{{.Names}}' | grep -q scientific-calculator
      register: container_exists
      ignore_errors: yes

    - name: Remove existing container
      shell: docker stop scientific-calculator && docker rm scientific-calculator
      when: container_exists.rc == 0
      ignore_errors: yes
        
    - name: Running container
      shell: docker run -d --name scientific-calculator -p 3000:3000 -p 5000:5000 scientific-calculator
